"""add exchange rate and base_amount

Revision ID: e73e1dd85c49
Revises: c546a2212003
Create Date: 2026-03-30 09:39:04.228875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e73e1dd85c49"
down_revision: Union[str, Sequence[str], None] = "c546a2212003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("base_amount", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "base_amount")
    # ### end Alembic commands ###
